---
- include: redhat.yaml
  when: ansible_os_family == 'RedHat'

- include: debian.yaml
  when: ansible_os_family == 'Debian'

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: Docker | Enable & start Docker daemon
  service:
    name: docker
    enabled: yes
    state: restarted
