---
- name: Docker | RedHat/CentOS | Install required docker packages
  yum:
    name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
    state: latest
  become: true

- name: Docker | RedHat/CentOS | Get docker .repo file
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Docker | RedHat/CentOS | Install Docker
  yum:
    name: "docker-ce"
    state: latest
